name = "auth-api"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Note: Utilisation temporaire du stockage en mémoire
# Les namespaces KV seront configurés dans une future mise à jour
# kv_namespaces = [
#   { binding = "USER_STORE", id = "your-kv-namespace-id-for-users" },
#   { binding = "TOKEN_STORE", id = "your-kv-namespace-id-for-tokens" }
# ]
