name = "auth-api"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Configuration KV namespaces pour l'authentification
kv_namespaces = [
  { binding = "USER_STORE", id = "452d484e-user-store-c25b7a32cc47" },
  { binding = "TOKEN_STORE", id = "452d484e-token-store-fb9e1c0a8e3d" }
]
