#!/usr/bin/env python3
"""
Country patterns for commodity correlator
Extracted for better performance and maintainability
"""

COUNTRY_PATTERNS = {
    "US": ["united states", "usa", "us ", "america", "washington", "white house"],
    "CN": ["china", "chinese", "beijing", "shanghai", "hong kong"],
    "AU": ["australia", "australian", "sydney", "melbourne", "canberra"],
    "FR": ["france", "french", "paris", "macron"],
    "DE": ["germany", "german", "berlin", "frankfurt"],
    "GB": ["uk", "united kingdom", "britain", "british", "london"],
    "JP": ["japan", "japanese", "tokyo", "yen"],
    "CA": ["canada", "canadian", "ottawa", "toronto"],
    "BR": ["brazil", "brazilian", "brasilia", "são paulo"],
    "IN": ["india", "indian", "delhi", "mumbai"],
    "RU": ["russia", "russian", "moscow", "kremlin", "putin"],
    "KR": ["korea", "korean", "seoul", "south korea"],
    "IT": ["italy", "italian", "rome", "milan"],
    "ES": ["spain", "spanish", "madrid", "barcelona"],
    "MX": ["mexico", "mexican", "mexico city"],
    "ID": ["indonesia", "indonesian", "jakarta"],
    "SA": ["saudi", "saudi arabia", "riyadh"],
    "AE": ["uae", "emirates", "dubai", "abu dhabi"],
    "AR": ["argentina", "argentine", "buenos aires"],
    "CL": ["chile", "chilean", "santiago"],
    "PE": ["peru", "peruvian", "lima"],
    "ZA": ["south africa", "johannesburg", "pretoria"],
    "NG": ["nigeria", "nigerian", "lagos", "abuja"],
    "EG": ["egypt", "egyptian", "cairo"],
    "TH": ["thailand", "thai", "bangkok"],
    "MY": ["malaysia", "malaysian", "kuala lumpur"],
    "SG": ["singapore", "singaporean"],
    "VN": ["vietnam", "vietnamese", "hanoi", "ho chi minh"],
    "PH": ["philippines", "philippine", "manila"],
    "PK": ["pakistan", "pakistani", "islamabad", "karachi"],
    "BD": ["bangladesh", "bangladeshi", "dhaka"],
    "TR": ["turkey", "turkish", "ankara", "istanbul"],
    "IR": ["iran", "iranian", "tehran"],
    "IQ": ["iraq", "iraqi", "baghdad"],
    "IL": ["israel", "israeli", "tel aviv", "jerusalem"],
    "UA": ["ukraine", "ukrainian", "kiev", "kyiv"],
    "PL": ["poland", "polish", "warsaw"],
    "NL": ["netherlands", "dutch", "amsterdam", "holland"],
    "BE": ["belgium", "belgian", "brussels"],
    "SE": ["sweden", "swedish", "stockholm"],
    "NO": ["norway", "norwegian", "oslo"],
    "DK": ["denmark", "danish", "copenhagen"],
    "FI": ["finland", "finnish", "helsinki"],
    "CH": ["switzerland", "swiss", "zurich", "geneva"],
    "AT": ["austria", "austrian", "vienna"],
    "GR": ["greece", "greek", "athens"],
    "PT": ["portugal", "portuguese", "lisbon"],
    "CZ": ["czech", "czech republic", "prague"],
    "HU": ["hungary", "hungarian", "budapest"],
    "RO": ["romania", "romanian", "bucharest"],
    "BG": ["bulgaria", "bulgarian", "sofia"],
    "HR": ["croatia", "croatian", "zagreb"],
    "IE": ["ireland", "irish", "dublin"],
    "NZ": ["new zealand", "kiwi", "auckland", "wellington"],
    "QA": ["qatar", "qatari", "doha"],
    "KW": ["kuwait", "kuwaiti"],
    "OM": ["oman", "omani", "muscat"],
    "JO": ["jordan", "jordanian", "amman"],
    "LB": ["lebanon", "lebanese", "beirut"],
    "MA": ["morocco", "moroccan", "rabat", "casablanca"],
    "TN": ["tunisia", "tunisian", "tunis"],
    "DZ": ["algeria", "algerian", "algiers"],
    "LY": ["libya", "libyan", "tripoli"],
    "SD": ["sudan", "sudanese", "khartoum"],
    "ET": ["ethiopia", "ethiopian", "addis ababa"],
    "KE": ["kenya", "kenyan", "nairobi"],
    "GH": ["ghana", "ghanaian", "accra"],
    "CI": ["ivory coast", "cote d'ivoire", "abidjan"],
    "CM": ["cameroon", "cameroonian", "yaounde"],
    "AO": ["angola", "angolan", "luanda"],
    "ZW": ["zimbabwe", "zimbabwean", "harare"],
    "ZM": ["zambia", "zambian", "lusaka"],
    "MZ": ["mozambique", "mozambican", "maputo"],
    "TZ": ["tanzania", "tanzanian", "dar es salaam"],
    "UG": ["uganda", "ugandan", "kampala"],
    "CD": ["congo", "drc", "kinshasa", "democratic republic"],
    "VE": ["venezuela", "venezuelan", "caracas"],
    "CO": ["colombia", "colombian", "bogota"],
    "EC": ["ecuador", "ecuadorian", "quito"],
    "BO": ["bolivia", "bolivian", "la paz"],
    "PY": ["paraguay", "paraguayan", "asuncion"],
    "UY": ["uruguay", "uruguayan", "montevideo"],
    "CU": ["cuba", "cuban", "havana"],
    "DO": ["dominican republic", "santo domingo"],
    "GT": ["guatemala", "guatemalan"],
    "HN": ["honduras", "honduran", "tegucigalpa"],
    "SV": ["el salvador", "salvadoran", "san salvador"],
    "NI": ["nicaragua", "nicaraguan", "managua"],
    "CR": ["costa rica", "costa rican", "san jose"],
    "PA": ["panama", "panamanian"],
    "JM": ["jamaica", "jamaican", "kingston"],
    "TT": ["trinidad", "tobago", "port of spain"],
    "LK": ["sri lanka", "sri lankan", "colombo"],
    "MM": ["myanmar", "burma", "burmese", "yangon"],
    "KH": ["cambodia", "cambodian", "phnom penh"],
    "LA": ["laos", "laotian", "vientiane"],
    "MN": ["mongolia", "mongolian", "ulaanbaatar"],
    "KZ": ["kazakhstan", "kazakh", "astana", "almaty"],
    "UZ": ["uzbekistan", "uzbek", "tashkent"],
    "TM": ["turkmenistan", "turkmen", "ashgabat"],
    "TJ": ["tajikistan", "tajik", "dushanbe"],
    "KG": ["kyrgyzstan", "kyrgyz", "bishkek"],
    "AZ": ["azerbaijan", "azerbaijani", "baku"],
    "AM": ["armenia", "armenian", "yerevan"],
    "GE": ["georgia", "georgian", "tbilisi"],
    "MD": ["moldova", "moldovan", "chisinau"],
    "BY": ["belarus", "belarusian", "minsk"],
    "LT": ["lithuania", "lithuanian", "vilnius"],
    "LV": ["latvia", "latvian", "riga"],
    "EE": ["estonia", "estonian", "tallinn"],
    "RS": ["serbia", "serbian", "belgrade"],
    "BA": ["bosnia", "bosnian", "sarajevo"],
    "MK": ["macedonia", "macedonian", "skopje"],
    "AL": ["albania", "albanian", "tirana"],
    "SI": ["slovenia", "slovenian", "ljubljana"],
    "SK": ["slovakia", "slovak", "bratislava"],
    "IS": ["iceland", "icelandic", "reykjavik"],
    "LU": ["luxembourg", "luxembourgish"],
    "MT": ["malta", "maltese", "valletta"],
    "CY": ["cyprus", "cypriot", "nicosia"],
    "LI": ["liechtenstein"],
    "AD": ["andorra"],
    "MC": ["monaco"],
    "SM": ["san marino"],
    "VA": ["vatican"],
    "GN": ["guinea", "guinean", "conakry"],
    "BF": ["burkina faso", "ouagadougou"],
    "ML": ["mali", "malian", "bamako"],
    "NE": ["niger", "nigerien", "niamey"],
    "TD": ["chad", "chadian", "n'djamena"],
    "MR": ["mauritania", "mauritanian", "nouakchott"],
    "SN": ["senegal", "senegalese", "dakar"],
    "GM": ["gambia", "gambian", "banjul"],
    "GW": ["guinea-bissau", "bissau"],
    "SL": ["sierra leone", "freetown"],
    "LR": ["liberia", "liberian", "monrovia"],
    "TG": ["togo", "togolese", "lome"],
    "BJ": ["benin", "beninese", "porto-novo"],
    "GA": ["gabon", "gabonese", "libreville"],
    "CG": ["congo", "republic of congo", "brazzaville"],
    "GQ": ["equatorial guinea", "malabo"],
    "CF": ["central african republic", "bangui"],
    "RW": ["rwanda", "rwandan", "kigali"],
    "BI": ["burundi", "burundian", "bujumbura"],
    "DJ": ["djibouti", "djiboutian"],
    "ER": ["eritrea", "eritrean", "asmara"],
    "SO": ["somalia", "somali", "mogadishu"],
    "SC": ["seychelles"],
    "MU": ["mauritius", "mauritian", "port louis"],
    "KM": ["comoros", "comorian", "moroni"],
    "MG": ["madagascar", "malagasy", "antananarivo"],
    "SZ": ["swaziland", "eswatini", "mbabane"],
    "LS": ["lesotho", "maseru"],
    "BW": ["botswana", "gaborone"],
    "NA": ["namibia", "namibian", "windhoek"],
    "MW": ["malawi", "malawian", "lilongwe"],
    "FJ": ["fiji", "fijian", "suva"],
    "PG": ["papua new guinea", "port moresby"],
    "SB": ["solomon islands", "honiara"],
    "VU": ["vanuatu", "port vila"],
    "NC": ["new caledonia", "noumea"],
    "PF": ["french polynesia", "tahiti", "papeete"],
    "GU": ["guam"],
    "MP": ["northern mariana", "saipan"],
    "AS": ["american samoa", "pago pago"],
    "PW": ["palau", "koror"],
    "FM": ["micronesia", "palikir"],
    "MH": ["marshall islands", "majuro"],
    "KI": ["kiribati", "tarawa"],
    "NR": ["nauru"],
    "TV": ["tuvalu", "funafuti"],
    "TO": ["tonga", "nuku'alofa"],
    "WS": ["samoa", "apia"],
    "CK": ["cook islands", "rarotonga"],
    "NU": ["niue"],
    "TK": ["tokelau"],
    "PN": ["pitcairn"],
    "WF": ["wallis and futuna"],
    "TL": ["timor-leste", "east timor", "dili"],
    "BN": ["brunei", "bandar seri begawan"],
    "MO": ["macau", "macao"],
    "HK": ["hong kong"],
    "TW": ["taiwan", "taipei"],
    "KP": ["north korea", "pyongyang"],
    "MV": ["maldives", "male"],
    "BT": ["bhutan", "thimphu"],
    "NP": ["nepal", "nepalese", "kathmandu"],
    "AF": ["afghanistan", "afghan", "kabul"],
    "YE": ["yemen", "yemeni", "sana'a", "sanaa"],
    "SY": ["syria", "syrian", "damascus"],
    "PS": ["palestine", "palestinian", "ramallah", "gaza"],
    "BH": ["bahrain", "bahraini", "manama"],
    "PR": ["puerto rico", "san juan"],
    "BB": ["barbados", "bridgetown"],
    "AG": ["antigua", "barbuda", "st. john's"],
    "DM": ["dominica", "roseau"],
    "GD": ["grenada", "st. george's"],
    "KN": ["st. kitts", "nevis", "basseterre"],
    "LC": ["st. lucia", "castries"],
    "VC": ["st. vincent", "grenadines", "kingstown"],
    "BS": ["bahamas", "bahamian", "nassau"],
    "BZ": ["belize", "belmopan"],
    "GY": ["guyana", "georgetown"],
    "SR": ["suriname", "paramaribo"],
    "GF": ["french guiana", "cayenne"],
    "FK": ["falkland islands", "stanley"],
    "GL": ["greenland", "nuuk"],
    "BM": ["bermuda", "hamilton"],
    "KY": ["cayman islands", "george town"],
    "TC": ["turks and caicos"],
    "VG": ["british virgin islands"],
    "VI": ["us virgin islands"],
    "AI": ["anguilla"],
    "MS": ["montserrat"],
    "GP": ["guadeloupe"],
    "MQ": ["martinique"],
    "AW": ["aruba"],
    "CW": ["curacao"],
    "SX": ["sint maarten"],
    "BQ": ["bonaire"],
    "HT": ["haiti", "haitian", "port-au-prince"],
    "RE": ["reunion"],
    "YT": ["mayotte"],
    "PM": ["st. pierre", "miquelon"],
    "SH": ["st. helena"],
    "IO": ["british indian ocean"],
    "CX": ["christmas island"],
    "CC": ["cocos islands"],
    "NF": ["norfolk island"],
    "HM": ["heard island"],
    "AQ": ["antarctica"],
    "BV": ["bouvet island"],
    "TF": ["french southern"],
    "GS": ["south georgia"],
    "UM": ["us minor outlying"],
    "EH": ["western sahara"],
    "SJ": ["svalbard"],
    "AX": ["aland islands"],
    "FO": ["faroe islands"],
    "GG": ["guernsey"],
    "JE": ["jersey"],
    "IM": ["isle of man"],
    "GI": ["gibraltar"]
}
