name: Classify Financial News with ML

on:
  # Exécution après la mise à jour des actualités
  workflow_run:
    workflows: ["Update Financial Data"]
    types:
      - completed
  # Exécution manuelle
  workflow_dispatch:
  # Exécution programmée (toutes les 6 heures)
  schedule:
    - cron: '0 */6 * * *'

# Ajout des permissions nécessaires
permissions:
  contents: write

jobs:
  classify-news:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ml/requirements.txt
      
      - name: Check if news.json exists
        id: check_files
        run: |
          if [ -f "data/news.json" ]; then
            echo "news_exists=true" >> $GITHUB_OUTPUT
          else
            echo "news_exists=false" >> $GITHUB_OUTPUT
            echo "Le fichier data/news.json n'existe pas. Création d'un fichier de test."
            mkdir -p data
            echo '{"us":[],"france":[],"events":[]}' > data/news.json
          fi
      
      - name: Run classification
        run: |
          python scripts/run_classification.py --input data/news.json
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Utilisez le token GITHUB_TOKEN pour l'authentification
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          git add data/news.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news with ML classification" && git push)