name: Data Updater

on:
  schedule:
    - cron: '15 6,14,22 * * *'  # 3 fois par jour à 6h15, 14h15, 22h15 UTC
  workflow_dispatch:  # Pour le déclenchement manuel

# Permissions nécessaires pour push
permissions:
  contents: write

jobs:
  update-financial-data:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout avec PAT pour pouvoir push
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupère tout l'historique
          token: ${{ github.token }}
      
      # Configuration de l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas
      
      # Synchronisation avec le dépôt distant
      - name: Sync with remote repository
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git pull origin main --rebase
      
      # Exécution du script Python
      - name: Run financial data update script
        run: python scripts/update_financial_data.py
      
      # Commit et push avec l'action dédiée
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "📊 Update financial data [automated]"
          add: "data/*.json"
          author_name: "GitHub Action Bot"
          author_email: "action@github.com"
          push: true
          github_token: ${{ github.token }}
          # La ligne force: true a été supprimée car non supportée par l'action
