name: Extract Stock Names

on:
  # Exécution manuelle depuis l'interface GitHub
  workflow_dispatch:
  
  # Exécution après la mise à jour des données unifiées
  workflow_run:
    workflows: ["Update Unified Lists"]
    types:
      - completed

jobs:
  extract-names:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run extraction script
        run: |
          python scripts/extract_stock_names.py
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/stock_names.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stock names data [skip ci]"
          git push
