name: Generate Glossary Index

on:
  # Permet de déclencher manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Message de commit pour la mise à jour'
        default: 'Mise à jour automatique de l''index du glossaire'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Pas de cache pour éviter l'erreur de fichier de verrou manquant
      
      - name: Install dependencies
        run: npm install
      
      - name: Create data directory if it doesn't exist
        run: mkdir -p data
      
      - name: Generate glossary index
        run: node scripts/buildGlossaryIndex.js
      
      - name: Check if glossary index exists
        id: check_file
        run: |
          if [ -f "data/glossary-index.json" ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/glossary-index.json
          
          if [ -f "report-missing-terms.txt" ]; then
            git add report-missing-terms.txt
          fi
          
          # Vérifier s'il y a des changements à commiter
          if git diff --staged --quiet; then
            echo "Aucun changement détecté, rien à commiter"
          else
            git commit -m "${{ github.event.inputs.commit_message }}"
            git push
          fi
