name: Process ML Feedback

on:
  # Déclenché manuellement
  workflow_dispatch:
  
  # Déclenché par un commit sur la branche principale contenant des feedbacks
  push:
    branches:
      - main
    paths:
      - 'data/ml_feedback.json'
      - 'data/ml_feedback_*.json'
  
  # Déclenché périodiquement pour traiter les feedbacks
  schedule:
    - cron: '0 2 * * *' # Tous les jours à 2h00 UTC

jobs:
  process-feedback:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas scikit-learn transformers torch
      
      - name: Process ML feedback data
        run: |
          python scripts/ml/process_feedback.py
        
      - name: Check for changes in feedback data
        id: check_changes
        run: |
          if git diff --name-only | grep -q "data/ml_feedback.json"; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi
      
      - name: Commit processed feedback data
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/ml_feedback.json
          git commit -m "Process ML feedback data [automated]"
          git push
