name: TradePulse Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Possibilité d'exécuter manuellement depuis l'interface GitHub
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      env:
        # Définir une clé API factice pour les tests
        API_CHAT: ${{ secrets.API_CHAT || 'test_api_key' }}
      run: |
        python -m unittest discover tests
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results/
          debug/prompts/
        if-no-files-found: ignore
