name: Update Crypto Data
on:
  schedule:
    - cron: '0 */12 * * *'  # Toutes les 12 heures (marché crypto 24/7)
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  update-crypto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          mkdir -p data
          
      - name: Run crypto scraper
        run: |
          python scripts/scrape_coinmarketcap.py
          
      - name: Check generated data
        run: |
          ls -la data/
          if [ -f "data/crypto_lists.json" ]; then
            echo "✅ Le fichier de données crypto a été généré avec succès"
            cat data/crypto_lists.json | head -n 20  # Affiche les 20 premières lignes pour vérification
          else
            echo "⚠️ Le fichier de données crypto n'a pas été généré"
            exit 1
          fi
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/crypto_lists.json
          git diff --staged --quiet || (git commit -m "Mise à jour automatique des données crypto" && git push)
