name: Update Financial Data

on:
  schedule:
    - cron: '10 5,13,21 * * *'  # 3 fois par jour
  workflow_dispatch:  # Permet de déclencher manuellement

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ajout de cette option pour obtenir l'historique complet
          fetch-depth: 0
          # Utilisation du token GitHub
          token: ${{ github.token }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas

      # Ajout d'une étape pour synchroniser avec le dépôt distant
      - name: Fetch latest changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase origin main
          
      - name: Run data update script
        run: python scripts/update_financial_data.py
        
      # Utilisation de git-auto-commit-action pour gérer les commits/push
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📊 Update financial data: $(date)"
          file_pattern: "data/*.json"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
          commit_author: "GitHub Action <action@github.com>"
          # Suppression de push_options: "--force" qui pourrait causer des problèmes
