name: Update Stock Data

on:
  schedule:
    # Exécuter plusieurs fois par jour en semaine (horaires de marchés)
    - cron: '30 8-16/2 * * 1-5'  # Toutes les 2 heures de 8h30 à 16h30 du lundi au vendredi
  workflow_dispatch:  # Permettre le déclenchement manuel

jobs:
  update_stock_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pour éviter les erreurs de réconciliation Git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create data directory if not exists
        run: mkdir -p data

      - name: Run unified stock lists update script
        run: |
          python update_unified_lists.py
          echo "Script executed at $(date)"

      - name: Commit and push changes
        run: |
          git add data/lists.json
          
          # Vérifier s'il y a des changements à committer
          if git diff --staged --quiet; then
            echo "Aucun changement à committer"
          else
            git commit -m "📊 Mise à jour unifiée des données NASDAQ et STOXX [skip ci]"
            
            # Pull avec stratégie de réconciliation pour éviter les conflits
            git pull --rebase --autostash
            
            # Push avec suivi des erreurs
            git push || {
              echo "Erreur lors du push, nouvelle tentative avec --force"
              git push --force
            }
          fi
