name: Update Financial Data

on:
  schedule:
    - cron: '10 5,13,21 * * *'  # 3 fois par jour (5h10, 13h10, 21h10) - légèrement décalé pour éviter les conflits
  workflow_dispatch:  # Permet de déclencher manuellement

# Ajout des permissions explicites
permissions:
  contents: write  # Autorise l'écriture dans le dépôt

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Récupérer tout l'historique pour faciliter le rebase
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas

      - name: Run data update script
        run: python scripts/update_financial_data.py
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "TradePulse Bot"
          git add data/
          if git diff --staged --quiet; then
            echo "No changes detected"
          else
            # Récupérer les derniers changements distants d'abord
            git pull --rebase origin main
            git commit -m "📊 Update financial data: $(date)"
            git push
          fi
