name: Update Lists Data

on:
  # Déclenchement manuel
  workflow_dispatch:
  # Ajout d'un déclenchement automatique toutes les 30 minutes
  schedule:
    - cron: '15,45 * * * *'  # Exécuter à 15e et 45e minute de chaque heure

# Configuration des permissions
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    # Définir un timeout plus court pour éviter les longues exécutions
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # S'assurer que l'action checkout récupère l'historat complet
          fetch-depth: 0
          # S'assurer que le token GitHub est utilisé pour l'authentification
          token: ${{ github.token }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Create data directory if needed
        run: mkdir -p data
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          # Désactiver les avertissements de certificat pour urllib3
          pip install urllib3
        
      - name: Copy markets data to lists data
        run: |
          if [ -f data/markets.json ]; then
            cp data/markets.json data/lists.json
            echo "Fichier markets.json copié vers lists.json"
          else
            echo "Fichier markets.json non trouvé, création d'un fichier vide"
            echo "{}" > data/lists.json
          fi
        
      - name: Verify data file exists
        run: |
          if [ ! -f data/lists.json ]; then
            echo "Fichier de données non trouvé, création d'un fichier vide"
            echo "{}" > data/lists.json
          fi
        
      - name: Commit and push if changed
        run: |
          # Configuration de git avec le token explicite
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Ajouter le fichier data/lists.json
          git add data/lists.json
          
          # Vérifier s'il y a des modifications à commiter
          if git diff --staged --quiet; then
            echo "Aucune modification détectée, pas de commit nécessaire"
          else
            echo "Modifications détectées, création d'un commit"
            git commit -m "Update lists data [skip ci]"
            
            # Utiliser le token GITHUB_TOKEN pour l'authentification
            git push origin HEAD:${GITHUB_REF}
          fi