name: Update Financial Data

on:
  # Déclenchement manuel
  workflow_dispatch:
  # Mise à jour automatique toutes les 4 heures
  schedule:
    - cron: '0 */4 * * *'

# Configuration des permissions
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Create data directory if needed
        run: mkdir -p data
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas
      
      # Étape 1: Récupération des actualités et événements via FMP
      - name: Update financial news and events from FMP
        id: update_fmp
        run: |
          echo "::group::Fetching data from Financial Modeling Prep API"
          python scripts/fmp_news_updater.py
          echo "::endgroup::"
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      
      # Étape 2: Vérification de la validité des données
      - name: Verify data format and quality
        run: |
          echo "::group::Validating data format"
          python -c "
          import json
          import os
          import sys

          # Vérifier l'existence du fichier news.json
          news_file = 'data/news.json'
          if not os.path.exists(news_file):
              print(f'❌ Erreur: Le fichier {news_file} n\'existe pas!')
              sys.exit(1)
              
          # Vérifier la validité et le contenu
          try:
              with open(news_file, 'r') as f:
                  data = json.load(f)
                  
              # Vérifier la structure
              if not isinstance(data, dict):
                  print('❌ Erreur: Format de données invalide - news.json n\'est pas un objet')
                  sys.exit(1)
                  
              # Vérifier les événements
              events = data.get('events', [])
              if not isinstance(events, list):
                  print('❌ Erreur: Format de données invalide - events n\'est pas une liste')
                  sys.exit(1)
                  
              # Vérifier qu'il y a au moins des événements
              if len(events) == 0:
                  print('⚠️ Avertissement: Aucun événement trouvé dans les données')
              else:
                  print(f'✅ Validation réussie: {len(events)} événements trouvés')
                  
              # Vérifier les news
              news = data.get('news', [])
              if not isinstance(news, list):
                  print('❌ Erreur: Format de données invalide - news n\'est pas une liste')
                  sys.exit(1)
                  
              # Vérifier qu'il y a au moins des news
              if len(news) == 0:
                  print('⚠️ Avertissement: Aucune actualité trouvée dans les données')
              else:
                  print(f'✅ Validation réussie: {len(news)} actualités trouvées')
                  
          except json.JSONDecodeError:
              print('❌ Erreur: Le fichier news.json n\'est pas un JSON valide')
              sys.exit(1)
          except Exception as e:
              print(f'❌ Erreur inattendue: {str(e)}')
              sys.exit(1)
              
          print('✅ Toutes les validations réussies!')
          "
          echo "::endgroup::"
        
      # Étape 3: Mise à jour des données de marché
      - name: Update market data
        run: |
          echo "::group::Updating market data"
          python scripts/scrape_markets.py
          echo "::endgroup::"
        continue-on-error: true
      
      # Étape 4: Génération de données de secours si nécessaire
      - name: Generate fallback data if needed
        run: |
          echo "::group::Checking for fallback data needs"
          python -c "
          import json
          import os
          import sys
          from datetime import datetime

          # Vérifier si les fichiers existent et leur taille
          news_file = 'data/news.json'
          markets_file = 'data/markets.json'
          
          needs_fallback = False
          
          # Vérifier news.json
          if not os.path.exists(news_file) or os.path.getsize(news_file) < 100:
              print('⚠️ Fichier news.json manquant ou trop petit, génération de secours nécessaire')
              needs_fallback = True
          
          # Vérifier markets.json  
          if not os.path.exists(markets_file) or os.path.getsize(markets_file) < 100:
              print('⚠️ Fichier markets.json manquant ou trop petit, génération de secours nécessaire')
              needs_fallback = True
              
          # Si un des fichiers a besoin de secours, générer des données de base
          if needs_fallback:
              print('🔄 Génération de données de secours en cours...')
              
              # Exemple de données de secours pour news.json
              if not os.path.exists(news_file) or os.path.getsize(news_file) < 100:
                  fallback_news = {
                      'lastUpdate': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                      'events': [
                          {
                              'title': 'Décision de taux d\\'intérêt (Fed)',
                              'date': datetime.now().strftime('%d/%m/%Y'),
                              'time': '14:00',
                              'type': 'economic',
                              'importance': 'high'
                          },
                          {
                              'title': 'Publication PIB trimestriel (US)',
                              'date': datetime.now().strftime('%d/%m/%Y'),
                              'time': '09:30',
                              'type': 'economic',
                              'importance': 'high'
                          }
                      ],
                      'news': [
                          {
                              'title': 'Les marchés réagissent aux nouvelles données économiques',
                              'date': datetime.now().strftime('%Y-%m-%d'),
                              'source': 'Fallback Data',
                              'url': '#',
                              'category': 'markets'
                          }
                      ]
                  }
                  
                  with open(news_file, 'w') as f:
                      json.dump(fallback_news, f, indent=2)
                  print(f'✅ Données de secours générées pour {news_file}')
              
              # Exemple de données de secours pour markets.json
              if not os.path.exists(markets_file) or os.path.getsize(markets_file) < 100:
                  fallback_markets = {
                      'lastUpdate': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                      'indices': [
                          {'name': 'S&P 500', 'value': '5200', 'change': '+0.2%'},
                          {'name': 'Nasdaq', 'value': '17000', 'change': '+0.3%'},
                          {'name': 'CAC 40', 'value': '8200', 'change': '-0.1%'}
                      ]
                  }
                  
                  with open(markets_file, 'w') as f:
                      json.dump(fallback_markets, f, indent=2)
                  print(f'✅ Données de secours générées pour {markets_file}')
          else:
              print('✅ Tous les fichiers de données sont présents et valides')
          "
          echo "::endgroup::"
      
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/'
          message: '📊 Update financial data via FMP API [automated]'
          default_author: github_actions
