name: Update Financial Data

on:
  schedule:
    - cron: '10 5,13,21 * * *'  # 3 fois par jour (5h10, 13h10, 21h10)
  workflow_dispatch:  # Permet de déclencher manuellement

# Ajout des permissions explicites
permissions:
  contents: write  # Autorise l'écriture dans le dépôt

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0  # Récupérer tout l'historique
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas

      - name: Run data update script
        run: python scripts/update_financial_data.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git add data/
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=changes_exist::true"
          else
            echo "::set-output name=changes_exist::false"
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_exist == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📊 Update financial data: $(date)"
          file_pattern: data/*
          commit_user_name: TradePulse Bot
          commit_user_email: action@github.com
          commit_author: TradePulse Bot <action@github.com>
          push_options: '--force'  # Utiliser force push si nécessaire
